[package]
name = "telegram-desktop"
version = "0.1.24"
description = "Standalone Telegram Desktop client"
authors = ["shareza2026-git"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

